name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Tag release (e.g., v1.0.0)"
        required: true
      branch:
        description: "Branch to build from"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Check Docker Info
        run: docker info

      - name: Build and push Docker image
        run: |
          docker build -t testing/welcome:latest -t testing/welcome:${{ github.event.inputs.release_tag }} .
          docker push testing/welcome:latest
          docker push testing/welcome:${{ github.event.inputs.release_tag }}
