name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "v1.0.0"
        required: true
      branch:
        description: "main"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build and push Docker image
        run: |
          docker build -t testing/welcome:latest -t testing/welcome:${{ github.event.inputs.release_tag }} .
          docker push testing/welcome:latest
          docker push testing/welcome:${{ github.event.inputs.release_tag }}
